version: "3.6"

services:
  ph1:
    image: registry.recfut.com/rf/application/main/integrations/phantom:4.9
    container_name: ph1
    ports:
      - "80:80"
      - "443:443"

#  event_generation:
#    build:
#      context: event_generation
#    container_name: event_generation
#    environment:
#      - RF_TOKEN=${RF_TOKEN}

#  squid:
#    image: sameersbn/squid:3.5.27-2
#    ports:
#      - 3128
#      - 3129
#    volumes:
#      - ./squid/squid.conf:/etc/squid/squid.conf
#      - ./squid/passwd:/etc/squid/passwd
#      - ./squid/cache:/var/spool/squid
#
#  test_api:
#    build:
#      context: testapi
#    environment:
#      - TEST_API_DEBUG=true
#      - TEST_API_SSL=adhoc
#      - TEST_API_HOST=0.0.0.0
#    container_name: test_api
#    ports:
#      - 5000
#    volumes:
#      - ../../common/test_api:/tmp/test_api%