version: "3.9"

services:
  rf_phantom:
    image: registry.recfut.com/rf/application/main/integrations/phantom:5.1
    container_name: rf_phantom
    ports:
      - "80:80"
      - "443:443"
      - "2022:22"
    cap_add:
      - ALL

  phantom_bfi:
    cap_add:
      - SYS_PTRACE
    build:
      context: phantom_bfi
    environment:
      - RF_TOKEN=${RF_TOKEN}
      - PHANTOM_BFI_SSL=adhoc
      - PHANTOM_BFI_HOST=0.0.0.0
      - entity_repository.url=https://sproxy.recfut.com/entity-repository/lookup
      - RF_ENV=premier_integrations
    container_name: phantom_bfi
    ports:
      - "5002:5002"
    volumes:
      - ${RF_HOME}/python:/tmp/python
      - ${RF_HOME}/conf:/tmp/conf

#  event_generation:
#    build:
#      context: event_generation
#    container_name: event_generation
#    environment:
#      - RF_TOKEN=${RF_TOKEN}

#  squid:
#    image: sameersbn/squid:3.5.27-2
#    ports:
#      - 3128
#      - 3129
#    volumes:
#      - ./squid/squid.conf:/etc/squid/squid.conf
#      - ./squid/passwd:/etc/squid/passwd
#      - ./squid/cache:/var/spool/squid
#
#  test_api:
#    build:
#      context: testapi
#    environment:
#      - TEST_API_DEBUG=true
#      - TEST_API_SSL=adhoc
#      - TEST_API_HOST=0.0.0.0
#    container_name: test_api
#    ports:
#      - 5000
#    volumes:
#      - ../../common/test_api:/tmp/test_api%
